services:
  db:
    image: postgres:16
    ports:
     - "127.0.0.1:55432:5432"
    container_name: basogol_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: basogol
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: basogol_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8002:8000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db

volumes:
  postgres_data:
