# Generated by Django 5.2.12 on 2026-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basogolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='department',
            field=models.CharField(default='tech', max_length=50),
        ),
    ]
